clc;
clear all;
dirData = 'sim_cbf_unitree_ros2_22_8_ts_19_43';
timeStamp = load([dirData '/timeStamp.csv']);
generalCounter = load([dirData '/generalCounter.csv']);
position = load([dirData '/position.csv']);
orientation = load([dirData '/orientation.csv']);
desLinVelocity = load([dirData '/desLinVelocity.csv']);
desAngVelocity = load([dirData '/desAngVelocity.csv']);
distance = load([dirData '/distance.csv']);
safety = load([dirData '/safety.csv']);
gradSafetyPosition = load([dirData '/gradSafetyPosition.csv']);
gradSafetyOrientation = load([dirData '/gradSafetyOrientation.csv']);
witnessDistance = load([dirData '/witnessDistance.csv']);
currentGoalPosition = load([dirData '/currentGoalPosition.csv']);
currentLidarPoints = processCell(load([dirData '/currentLidarPoints.csv']));
currentLidarPointsKDTree = processCell(load([dirData '/currentLidarPointsKDTree.csv']));
currentOmega = load([dirData '/currentOmega.csv']);
planningState = load([dirData '/planningState.csv']);
graphNodes = processCell(load([dirData '/graphNodes.csv']));
graphEdges = processCell(load([dirData '/graphEdges.csv']));
pointsKDTree = processCell(load([dirData '/pointsKDTree.csv']));
pointsFrontier = processCell(load([dirData '/pointsFrontier.csv']));
currentPath = processCell(load([dirData '/currentPath.csv']));
currentIndexPath = load([dirData '/currentIndexPath.csv']);
explorationPosition = load([dirData '/explorationPosition.csv']);
messages = processMessageTable(readtable([dirData '/messages.csv']),generalCounter);
commitedPos = processCell(load([dirData '/commitedPos.csv']));
commitedOri = processCell(load([dirData '/commitedOri.csv']));
run sim_cbf_unitree_ros2_22_8_ts_19_43/parameters.m;
